---
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-pip
  sudo: True

- name: Install flexget pip dependencies
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - { name: 'six', version: '1.9.0' }
    - { name: 'subliminal', version: '1.0.1' }
  sudo: True

- name: Install flexget
  pip: name=flexget
  sudo: True

- name: Install transmissionrpc
  pip: name=transmissionrpc
  sudo: True

- name: Create flexget config folder
  file: path={{ user_home }}/.flexget state=directory mode='u=rwx,g=rx'

- name: Copy flexget configuration
  template: src={{ item }}.j2 dest={{ user_home }}/.flexget/{{ item }} mode='u=rw,g=rw'
  with_items:
    - config.yml
    - series.yml
    - animes.yml

- name: Add flexget to the crontab
  cron: name='run flexget' special_time=hourly job='/usr/local/bin/flexget --cron execute' state=present
