---
- hosts: all
  vars:
    rvm1_rubies:
            - 'ruby-2.2.3'
    rvm1_rvm_check_for_updates: False
    transmission_peer_port: '51413'
    transmission_initial_port: '49152'
    transmission_final_port: '65535'
    transmission_complete_folder: '/var/lib/transmission-daemon/complete'
    series_folder: 'Series'
  vars_files:
    - vars/credentials.yml
  remote_user: pi
  roles:
    - common
    - nginx
    - { role: rvm_io.rvm1-ruby, sudo: True }
    - pia
    - transmission
    - flexget
