---
- hosts: all
  vars_files:
    - vars/common.yml
    - vars/credentials.yml
  remote_user: osmc
  roles:
    - common
    - nginx
    - { role: rvm_io.rvm1-ruby, sudo: True }
    - pia
    - transmission
    - flexget
    - kodi
