---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.

- hosts: all
  vars:
    rvm1_rubies:
            - 'ruby-2.2.3'
    rvm1_rvm_check_for_updates: False
    transmission_initial_port: '16384'
    whitelisted_last_port: '16383'
  remote_user: pi
  roles:
    - common
    - nginx
    - { role: rvm_io.rvm1-ruby, sudo: True }
    - pia
    - ferm
