- name: Install ufw
  apt: name=ufw state=present
  sudo: True

- name: Reset to default config
  ufw: state=reset
  sudo: True

- name: Deny all incoming traffic by default
  ufw: direction=incoming policy=deny
  sudo: True

- name: Deny all outgoing traffic by default
  ufw: direction=outgoing policy=deny
  sudo: True


- name: Allow incoming traffic through the vpn
  ufw: direction=in interface=tun0 rule=allow
  sudo: True

- name: Allow outgoing traffic through the vpn
  ufw: direction=out interface=tun0 rule=allow
  sudo: True

- name: Allow creation of VPN tunnel
  ufw: direction=out port={{ vpn_port }} rule=allow
  sudo: True

- name: Allow needed ports for incoming
  ufw: port={{ item }} rule=allow direction=in
  with_items: "{{ ports }}"
  sudo: True

- name: Allow needed ports for outgoing
  ufw: port={{ item }} rule=allow direction=out
  with_items: "{{ ports }}"
  sudo: True

- name: Allow local ipv4 incoming connections
  ufw: rule=allow src={{ item }} direction=in
  with_items: "{{ ipv4_addresses }}"
  sudo: True

- name: Allow local ipv4 outgoing connections
  ufw: rule=allow src={{ item }} direction=out
  with_items: "{{ ipv4_addresses }}"
  sudo: True

- name: Allow ipv4 incoming multicasts
  ufw: rule=allow src={{ item }} direction=in
  with_items: "{{ ipv4_multicasts }}"
  sudo: True

- name: Allow ipv4 outgoing multicasts
  ufw: rule=allow src={{ item }} direction=out
  with_items: "{{ ipv4_multicasts }}"
  sudo: True

- name: Allow local ipv6 incoming connections
  ufw: rule=allow src={{ item }} direction=in
  with_items: "{{ ipv6_addresses }}"
  sudo: True

- name: Allow local ipv6 outgoing connections
  ufw: rule=allow src={{ item }} direction=out
  with_items: "{{ ipv6_addresses }}"
  sudo: True

- name: Allow ipv6 incoming multicasts
  ufw: rule=allow src={{ item }} direction=in
  with_items: "{{ ipv6_multicasts }}"
  sudo: True

- name: Allow ipv6 outgoing multicasts
  ufw: rule=allow src={{ item }} direction=out
  with_items: "{{ ipv6_multicasts }}"
  sudo: True

- name: Reload ufw
  ufw: state=enabled
  sudo: True

