- name: Install ufw
  apt: name=ufw state=present
  sudo: True

- name: Reset to default config
  ufw: state=reset
  sudo: True

- name: Deny all incoming traffic by default
  ufw: direction=incoming policy=deny
  sudo: True

- name: Deny all outgoing traffic by default
  ufw: direction=outgoing policy=deny
  sudo: True


- name: Allow incoming traffic through the vpn
  ufw: direction=in interface=tun0 rule=allow
  sudo: True

- name: Allow outgoing traffic through the vpn
  ufw: direction=out interface=tun0 rule=allow
  sudo: True

- name: Allow creation of VPN tunnel
  ufw: direction=out port={{ vpn_port }} rule=allow
  sudo: True

- name: Allow needed ports for incoming connections
  ufw: port={{ item }} rule=allow direction=out
  with_items:
    - 53
    - 5353
    - 80
    - 443
    - "{{ transmission_rpc_port }}"
  sudo: True

- name: Allow needed ports for outgoing connections
  ufw: port={{ item }} rule=allow direction=out
  with_items:
    - 53
    - 5353
    - 80
    - 443
    - "{{ transmission_rpc_port }}"
  sudo: True

- name: Allow local connections
  ufw: rule=allow src={{ item }}
  with_items:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  sudo: True

- name: Reload ufw
  ufw: state=enabled
  sudo: True

