---
- name: Create kodi folder
  file: path={{ user_home }}/kodi state=directory

- name: Detect kodi source folder
  stat: path={{ user_home }}/kodi/kodi-15
  register: kodi_src

- name: Unarchive kodi source
  unarchive: src=kodi-15.1-wheezy.tar.gz dest={{ user_home }}/kodi/
  when: not kodi_src.stat.exists

- name: Create input group
  group: name=input state=present system=yes
  sudo: True

- name: Create udev rules
  template: src=99-input.rules dest=/etc/udev/rules.d/99-input.rules owner=root group=root
  with_items:
    - '99-input.rules'
    - '10-permissions.rules'
  sudo: True

- name: Add pi to all groups it needs
  user: name=pi groups=pi,root,cdrom,floppy,sudo,audio,dip,video,plugdev,netdev,input,dialout,tty
  sudo: True

- name: Copy boot config file
  template: src=boot_config.txt dest=/boot/config.txt owner=root group=root mode='u=rw,g=rw,o=rw'
  sudo: True


- name: Install dependencies
  apt: name=gdebi-core state=present

- name: Uninstall too new packages
  apt: name='{{ item }}' state=absent
  with_items:
    - cec-utils
    - libcec1
    - libcec2
    - libcec-dev
    - libcec3
  sudo: True

- name: Install libplatform1
  apt: deb={{ user_home }}/kodi/kodi-15/libplatform1_1.0.9-1_armhf.deb state=present
  sudo: True

- name: Install libcec3
  apt: deb={{ user_home }}/kodi/kodi-15/libcec3_3.0.1-1_armhf.deb state=present
  sudo: True

- name: Install kodi
  apt: deb={{ user_home }}/kodi/kodi-15/kodi_15.1-150901-3_armhf.deb state=present
  sudo: True

- name: Copy startkodi to /usr/local/bin
  copy: src=startkodi dest=/usr/local/bin/startkodi owner=root group=root mode='u=rwx,g=rx,o=rx'
  sudo: True
