---
- name: Update apt cache if older than a day
  apt: update_cache=yes cache_valid_time=86400
  sudo: True

- name: Install common packages
  apt: name={{ item }} state=present
  environment:
    PATH: /bin:/sbin:/usr/bin:/usr/sbin
  with_items:
    - vim
    - ntfs-3g
    - curl
    - cron
  sudo: True

- name: Create bin folder for main user
  file: path={{ user_home }}/bin state=directory

- name: Copy profile for main user
  template: src=bash_profile dest={{ user_home }}/.bash_profile

- name: Enable cron
  service: name=cron enabled=true
  sudo: True

- name: Start cron
  service: name=cron state=started
  sudo: True
