---
- name: Install common packages
  apt: name={{ item }} state=present
  with_items:
    - vim
    - ntfs-3g
    - curl
  sudo: True

- name: Create bin folder for pi user
  file: path=/home/pi/bin state=directory
